### ISSUE TITLE
Getting "Bad Syntax" error when using >>=?

### ISSUE THREAD

**Issue by capn-freako** [sighingnow/parsec.py#50]
I'm trying to use `>>=` as an infix shortcut for `bind()`, but when I do the Python interpreter (3.8) complains that it is incorrect syntax.
I've created the following _StackOverflow_ question on this:

https://stackoverflow.com/questions/70628660/why-am-i-getting-a-syntax-error-when-using-the-operator

**Comment by sighingnow** [comment]
As explained in the stackoverflow tickets, the `>>=` is an _inplace_ operator.

It could be improved, as `>=` might be a better symbol here for `bind()`.

**Comment by sighingnow** [comment]
The issue has been fixed and I have uploaded a new version to pypi.

**Comment by capn-freako** [comment]
Hmmm, I updated to your new version, but am still getting the same syntax error:

```
$ pip install parsec --no-deps --pre -U -I
Collecting parsec
  Downloading parsec-3.12-py2.py3-none-any.whl (13 kB)
Installing collected packages: parsec
Successfully installed parsec-3.12

$ conda list parsec
# packages in environment at /Users/dbanas/opt/anaconda3/envs/pybert:
#
# Name                    Version                   Build  Channel
parsec                    3.12                     pypi_0    pypi

$ ./irshift_debug.py
  File "./irshift_debug.py", line 9
    testp = digit() >>= id
                    ^
SyntaxError: invalid syntax
```

Here is the contents of my `irshift_debug.py` file:

```python
#! /usr/bin/env python

from parsec import *

def id(x):
    """Identity parser."""
    return string("").result(x)

testp = digit() >>= id
# testp = digit().bind(id)

print(testp.parse("5"))
```
